baseURL = "https://runningturtle1.github.io/mysimplyagenda/"
languageCode = "fr"
title = "My New Hugo Site"
staticDir = "mysimplyagenda"
[menu]
  [[menu.main]]
    name = "Accueil"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Articles"
    pre = "pen-tool"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Fonctionnalit√©s"
    pre = "tag"
    url = "/features/"
    weight = 3
